ip: xx.xx.xx.xx
#指定服务端口
server:
  port: 8080
spring:
  #mysql数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/footmap?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  main:
    allow-bean-definition-overriding: true
  #redis配置
  redis:
    host: xx.xx.xx.xx
    database: 1
    port: 6379
    password: 12345678
    jedis:
      pool:
        max-active: 8  #连接池最大数量
        max-wait: -1 #连接池最大阻塞时间(负值没有限制)
        max-idle: 8 #连接池最大空闲连接
        min-idle: 0 #连接池最小空闲连接
    timeout: 3000ms #连接超时时间
  #freemarker模板配置
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    content-type: text/html
    charset: UTF-8

mybatis:
  type-aliases-package: com/wenghuangge/mapper
  mapperLocations: classpath:mapper/*.xml

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - xx.xx.xx.xx:22122
  web-server-url: http://${ip}:80/